const ERROR_CODES = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    INVALID_ID: "INVALID_ID",
    DUPLICATE_KEY: "DUPLICATE_KEY",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",

    EVENT_NOT_FOUND: "EVENT_NOT_FOUND",
    EVENT_TEMPLATE_NOT_FOUND: "EVENT_TEMPLATE_NOT_FOUND",
};

module.exports = ERROR_CODES;